### ISSUE TITLE
Markdown plugin included but not working

### ISSUE THREAD

**Issue by qznc** [kentonv/etherpad-lite#22]
Using version 1.5.7 from 2015 Aug 16, which is in [in the app market](https://apps.sandstorm.io/app/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60).

When creating a new grain, the plugin ep_markdown seems to be included according to the initial pad content:

> This version of Etherpad includes the following plugins: ep_align ep_author_neat ep_comments_page ep_font_color ep_font_family ep_font_size ep_headings2 ep_markdown ep_page_view ep_print ep_spellcheck ep_sticky_attributes ep_subscript_and_superscriptd

However, there seems to be no way to use it. 

There should be a "view markdown" option in the settings.
![screenshot 2016-04-14](https://cloud.githubusercontent.com/assets/91316/14521712/085ccee4-022b-11e6-823d-aafb2cf8398c.png)

There should be a "markdown export" option.
![screenshot 2016-04-14](https://cloud.githubusercontent.com/assets/91316/14521713/08604f74-022b-11e6-90c9-7e0995631b7c.png)

**Comment by kentonv** [comment]
Sorry, the bug here is in the default text. The ep_markdown plugin was removed from the plugin list, but the text wasn't updated. See: #19 

I removed the ep_markdown plugin in the last release because the functionality it provided was actually the opposite of what most people wanted: enabling markdown mode caused it to render your rich-text as if it were markdown (e.g. adding # characters in front of headings), but it did not allow you to type your own markdown. This confused people and seemed not very useful.

Do you feel differently about the ep_markdown plugin?

**Comment by qznc** [comment]
Ah, I read "not actually included anymore" in #19 as "text not included in startup text anymore" and was confused that I did see it.

What I would need is Markdown export. I don't care about writing in Markdown.

**Comment by kentonv** [comment]
ep_markdown was re-enabled in the July 11 release. The behavior is still strange to me, but it seems to be strange upstream too...
